version: '3.1'

services:
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "25432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - mse-network

networks: 
  mse-network:
    driver: bridge

volumes:
  pgdata:
    driver: local